spring:
  shardingsphere:
    datasource:
      names: datasource1,datasource1slave
      datasource1:
        type: org.apache.commons.dbcp2.BasicDataSource
        url: jdbc:mysql://127.0.0.1:3306/datasource1?useUnicode=true&characterEncoding=utf-8
        username: root
        password: password
      datasource1slave:
        type: org.apache.commons.dbcp2.BasicDataSource
        url: jdbc:mysql://127.0.0.1:3306/datasource1_slave?useUnicode=true&characterEncoding=utf-8
        username: root
        password: password
    masterslave:
      name: ms
      master-data-source-name: datasource1
      slave-data-source-names: datasource1slave
    props:
      sql:
        show: true
  dynamic:
    datasource:
      datasource2:
        jdbc-url: jdbc:mysql://127.0.0.1:3306/datasource2?useUnicode=true&characterEncoding=utf-8
        username: root
        password: password

logging:
  level:
    root: info
    com.shenjies88.practice.multipledatasource: debug
    com.shenjies88.practice.multipledatasource.data1mapper: debug
    com.shenjies88.practice.multipledatasource.data2mapper: debug