spring:
  shardingsphere:
    datasource:
      - name: datasource1
        url: jdbc:mysql://127.0.0.1:3306/datasource1?useUnicode=true&characterEncoding=utf-8
        username: root
        password: password
        master: true
      - name: datasource1_slave
        url: jdbc:mysql://127.0.0.1:3306/datasource1_slave?useUnicode=true&characterEncoding=utf-8
        username: root
        password: password
        master: false
  dynamic:
    datasource:
      datasource2:
        jdbc-url: jdbc:mysql://127.0.0.1:3306/datasource2?useUnicode=true&characterEncoding=utf-8
        username: root
        password: password

logging:
  level:
    root: info
    com.shenjies88.practice.multipledatasource: debug
    com.shenjies88.practice.multipledatasource.data1mapper: debug
    com.shenjies88.practice.multipledatasource.data2mapper: debug